# Modified from: https://github.com/cclauss/Find-Python-syntax-errors-action

on: push
name: Check Code
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
      if: 
        ${{ success() }} == false:
          ## create pull request so errors can be corrected
        